kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  namespace: af-connect-cicd
  name: af-connect-demo
spec:
  nodeSelector: {}
  triggers: []
  output:
    to:
      kind: ImageStreamTag
      name: 'af-connect-demo:latest'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: HOST
          value: localhost
        - name: PORT
          value: '3000'
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/MagnumOpuses/af-connect-demo.git'
      ref: jenkins/deploy