apiVersion: v1
kind: Service
metadata:
  name: af-connect-demo
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    deploymentconfig: af-connect-demo
  type: ClusterIP